# Generated by Django 3.1 on 2020-08-17 16:06

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200817_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('misc', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(classname='full title', help_text='Blog Heading')), ('sub_title', wagtail.core.blocks.RichTextBlock(help_text='Page sub-content'))])), ('paragraph', wagtail.core.blocks.RichTextBlock(help_text='Your body content', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Attach any image')), ('gallery', wagtail.core.blocks.StructBlock([('images', wagtail.core.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock()))])), ('button', wagtail.core.blocks.StructBlock([('button_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('button_url', wagtail.core.blocks.URLBlock(help_text='Used to link to the page above', required=False))]))], null=True),
        ),
    ]
