# Generated by Django 3.1 on 2020-08-17 17:14

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('home', '0004_auto_20200817_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('misc', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(classname='full title', help_text='Blog Heading')), ('sub_title', wagtail.core.blocks.RichTextBlock(help_text='Page sub-content'))])), ('column', wagtail.core.blocks.StructBlock([('paragraph', wagtail.core.blocks.RichTextBlock(help_text='Your body content')), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Attach any image', required=True))])), ('button', wagtail.core.blocks.StructBlock([('button_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('button_url', wagtail.core.blocks.URLBlock(help_text='Used to link to the page above', required=False))]))], null=True),
        ),
        migrations.CreateModel(
            name='HomePageImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
