# Generated by Django 3.1 on 2020-08-17 17:22

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200817_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageimage',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='home.homepage'),
        ),
    ]
